codecov:
  token: "943037bd-242e-43ca-870b-76382d238188"
  bot: "codecov-io"
  ci:
    - "circleci"
  strict_yaml_branch: "yaml-config"
  max_report_age: 24
  disable_default_path_fixes: no
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes