version: 2.1
orbs:
  welcome: circleci/welcome-orb@0.4.1
workflows:
  push:
    jobs:
      build:
        docker:
          - image: circleci/node:12.18.3

        working_directory: ~/repo

        steps:
          - checkout
          - restore_cache:
              keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-

          - run: npm install

          - save_cache:
              paths:
                - node_modules
              key: v1-dependencies-{{ checksum "package.json" }}

          - run: npm test